const fs = require('fs');

const rawUnits = [
// Unit 12
`abandon|v. 放棄
abide|v. 遵守
abolish|v. 廢除
abroad|adv. 在國外
abrupt|adj. 突然的
absence|n. 缺席
absolute|adj. 絕對的
absorb|v. 吸收
abstract|adj. 抽象的
abundant|adj. 豐富的
abuse|v. 濫用
accelerate|v. 加速
acceptable|adj. 可接受的
acceptance|n. 接受
accessible|adj. 易接近的
accidental|adj. 意外的
acclaim|v. 稱讚
accommodate|v. 容納；提供住宿
accomplish|v. 完成
accord|n. 協議
account|n. 帳戶
accountant|n. 會計師
accumulate|v. 累積
accuracy|n. 準確性
accurate|adj. 準確的
accuse|v. 指控
accustom|v. 使習慣
achieve|v. 達成
achievement|n. 成就
acknowledge|v. 承認
acquire|v. 取得；收購
acquisition|n. 收購
activate|v. 啟動
active|adj. 活躍的
actual|adj. 實際的
adapt|v. 適應
addict|n. 上癮者
addition|n. 增加
additional|adj. 額外的
address|v. 處理；對...演說
adequate|adj. 充足的
adhere|v. 堅持；黏著
adjacent|adj. 鄰近的
adjust|v. 調整
administer|v. 管理
administration|n. 管理；行政
administrative|adj. 行政的
admire|v. 欽佩
admission|n. 入場費；承認
admit|v. 承認
adopt|v. 採納
advance|v. 前進
advanced|adj. 先進的
advantage|n. 優勢
advantageous|adj. 有利的
advent|n. 出現
adventure|n. 冒險
adverse|adj. 不利的
advertise|v. 登廣告
advertisement|n. 廣告
advice|n. 建議
advise|v. 建議
adviser|n. 顧問
advocate|v. 提倡
affair|n. 事務
affect|v. 影響
affiliate|v. 附屬
affirm|v. 確認
afford|v. 負擔得起
affordable|adj. 負擔得起的
agency|n. 代理機構
agenda|n. 議程
agent|n. 代理人
aggravate|v. 惡化
aggressive|adj. 積極的
agreement|n. 協議；合約
agriculture|n. 農業
aid|n. 援助
airline|n. 航空公司
aisle|n. 走道
alert|adj. 警覺的
alienate|v. 使疏遠
align|v. 使結盟
alike|adj. 相似的
allege|v. 宣稱
alleviate|v. 減輕
allocate|v. 分配；撥出
allow|v. 允許
allowance|n. 津貼
allude|v. 暗示
ally|n. 盟友
alter|v. 改變
alternate|v. 交替
alternative|n. 替代方案
altitude|n. 高度
amateur|n. 業餘愛好者
amaze|v. 使驚訝
ambassador|n. 大使
ambiguity|n. 模稜兩可
ambiguous|adj. 模糊不清的
ambition|n. 抱負
ambitious|adj. 有野心的
amend|v. 修改
amendment|n. 修正；修訂
amount|n. 數量
ample|adj. 充足的
amplify|v. 放大
amuse|v. 使歡樂
analogy|n. 類比
analysis|n. 分析
analyze|v. 分析
ancestor|n. 祖先
anchor|n. 錨；主播
ancient|adj. 古代的
anecdote|n. 軼事
angle|n. 角度
angry|adj. 生氣的
anguish|n. 極度痛苦
animate|v. 賦予生命
anniversary|n. 週年紀念日
announce|v. 宣佈
announcement|n. 公告
annoy|v. 惹惱
annual|adj. 每年的
anomalous|adj. 異常的
anonymous|adj. 匿名的
answer|v. 回答
antagonism|n. 敵意
anticipate|v. 預期
anticipation|n. 預期
antique|n. 古董
anxiety|n. 焦慮
anxious|adj. 焦慮的
apologize|v. 道歉
apology|n. 道歉
appalling|adj. 令人震驚的
apparatus|n. 設備
apparent|adj. 明顯的
appeal|v. 呼籲；吸引
appealing|adj. 吸引人的
appear|v. 出現
appearance|n. 外表
appendix|n. 附錄
appetite|n. 胃口
applaud|v. 鼓掌
appliance|n. 家電
applicable|adj. 適用的
applicant|n. 申請人
application|n. 申請
apply|v. 申請
appoint|v. 任命
appointment|n. 約會；任命
appraisal|n. 評估；考核
appraise|v. 評估
appreciate|v. 欣賞；感激
appreciation|n. 感謝
apprehend|v. 逮捕
apprentice|n. 學徒
approach|v. 接近
appropriate|adj. 適當的
approval|n. 批准
approve|v. 批准
approximate|adj. 大約的
aptitude|n. 天資
arbitrary|adj. 任意的
architect|n. 建築師
architecture|n. 建築
archive|n. 檔案
area|n. 區域
argue|v. 爭論
argument|n. 爭論
arise|v. 產生
arm|n. 手臂；武器
arouse|v. 喚醒
arrange|v. 安排
arrangement|n. 安排
array|n. 一系列
arrest|v. 逮捕
arrival|n. 到達
arrive|v. 到達
arrogant|adj. 傲慢的
article|n. 文章；物品
artificial|adj. 人造的
artisan|n. 工匠
artist|n. 藝術家
ascertain|v. 查明
aspect|n. 方面
aspire|v. 渴望
assemble|v. 組裝；集合
assembly|n. 集會；組裝
assert|v. 斷言
assess|v. 評估
assessment|n. 評估
asset|n. 資產
assign|v. 分配`,

// Unit 13
`assignment|n. 任務
assimilate|v. 吸收
assist|v. 協助
assistance|n. 協助
assistant|n. 助手
associate|v. 關聯
association|n. 協會
assortment|n. 各式各樣
assume|v. 假設
assumption|n. 假設
assure|v. 保證
astonish|v. 使驚訝
astound|v. 使震驚
attach|v. 附上；附加
attachment|n. 附件
attack|v. 攻擊
attain|v. 達到
attempt|v. 嘗試
attend|v. 出席
attendance|n. 出席率
attendee|n. 出席者
attention|n. 注意
attentive|adj. 專心的
attract|v. 吸引
attraction|n. 吸引力
attractive|adj. 吸引人的
attribute|v. 歸因於
auction|n. 拍賣
audience|n. 觀眾
audit|n. 審計；v. 查帳
auditor|n. 審計員
authentic|adj. 真實的
author|n. 作者
authority|n. 權威
authorization|n. 授權
authorize|v. 授權；批准
auto|n. 汽車
autograph|n. 簽名
automate|v. 使自動化
automatic|adj. 自動的
automation|n. 自動化
automobile|n. 汽車
autonomous|adj. 自治的
availability|n. 可用性；空檔
available|adj. 可用的
avenue|n. 大道
average|adj. 平均的
avoid|v. 避免
await|v. 等候
awake|adj. 醒著的
award|n. 獎
aware|adj. 意識到的
awareness|n. 意識
awful|adj. 糟糕的
awkward|adj. 尷尬的
backdrop|n. 背景
background|n. 背景
backlog|n. 積壓的工作
backup|n. 備份
baggage|n. 行李
balance|n. 餘額；平衡
ballot|n. 選票
ban|v. 禁止
band|n. 樂團
bankrupt|adj. 破產的
bankruptcy|n. 破產
banner|n. 橫幅
banquet|n. 宴會
bare|adj. 裸露的
barely|adv. 幾乎不
bargain|n. 交易；便宜貨
barrier|n. 障礙
base|n. 基礎
basic|adj. 基本的
basis|n. 基礎
bear|v. 忍受；承擔
beat|v. 擊敗
behalf|n. 代表
behave|v. 表現
behavior|n. 行為
belongings|n. 財產
below|prep. 在...之下
benchmark|n. 基準
beneficial|adj. 有益的
benefit|n. 福利；利益
beside|prep. 在...旁邊
besides|adv. 此外
betray|v. 背叛
beverage|n. 飲料
beyond|prep. 超過
bias|n. 偏見
bid|n. 投標；v. 出價
bill|n. 帳單
bind|v. 綁
biography|n. 傳記
biology|n. 生物學
bitter|adj. 苦的
blame|v. 責備
blank|adj. 空白的
blanket|n. 毛毯
blast|n. 爆炸
blend|v. 混合
blind|adj. 瞎的
block|n. 街區
bloom|v. 開花
board|n. 董事會；v. 登機
boast|v. 吹噓
bold|adj. 大膽的
bond|n. 債券
bonus|n. 獎金
booklet|n. 小冊子
boom|n. 繁榮
boost|v. 促進
booth|n. 攤位；小隔間
border|n. 邊界
bother|v. 打擾
bottom|n. 底部
bounce|v. 彈跳
bound|adj. 綁住的
boundary|n. 邊界
branch|n. 分支
brand|n. 品牌
brave|adj. 勇敢的
breach|n. 違反
break|n. 休息
breakdown|n. 故障
breakthrough|n. 突破
breathe|v. 呼吸
brief|adj. 簡短的
briefcase|n. 公事包
briefing|n. 簡報
brilliant|adj. 輝煌的
bring|v. 帶來
broad|adj. 寬廣的
broadcast|v. 廣播
broaden|v. 變寬
brochure|n. 小冊子
broker|n. 經紀人
browse|v. 瀏覽
browser|n. 瀏覽器
budget|n. 預算
build|v. 建築
building|n. 建築物
bulk|n. 體積；大量
bulletin|n. 公告
bunch|n. 串
bundle|n. 束
burden|n. 負擔
bureau|n. 局
burn|v. 燃燒
burst|v. 爆裂
business|n. 商業
button|n. 按鈕
bypass|v. 繞過
cabinet|n. 櫥櫃
cable|n. 電纜
calculate|v. 計算
calculation|n. 計算
calculator|n. 計算機
calendar|n. 日曆
campaign|n. 活動
campus|n. 校園
cancel|v. 取消
cancellation|n. 取消
candidate|n. 候選人；應徵者
canvas|n. 帆布
capable|adj. 有能力的
capacity|n. 容量；能力
capital|n. 資本
capture|v. 捕捉
carbon|n. 碳
care|n. 照顧
career|n. 職業
careful|adj. 小心的
careless|adj. 粗心的
cargo|n. 貨物
carrier|n. 運輸工具
carry|v. 攜帶
cart|n. 手推車
case|n. 情況
cash|n. 現金
cashier|n. 收銀員
catalog|n. 目錄
catch|v. 抓
category|n. 類別
cater|v. 迎合
catering|n. 外燴服務
cause|n. 原因
caution|n. 警告
cautious|adj. 謹慎的
cease|v. 停止
ceiling|n. 天花板`,

// Unit 14
`celebrate|v. 慶祝
celebration|n. 慶典
celebrity|n. 名人
cell|n. 細胞
censor|v. 審查
census|n. 人口普查
center|n. 中心
central|adj. 中央的
century|n. 世紀
ceremony|n. 典禮
certain|adj. 確定的
certainly|adv. 確實地
certificate|n. 證書
certification|n. 證明
certify|v. 證明
chain|n. 鏈
chair|n. 椅子
chairman|n. 主席
challenge|n. 挑戰
chamber|n. 房間
champion|n. 冠軍
championship|n. 錦標賽
chance|n. 機會
change|v. 改變
channel|n. 頻道
chaos|n. 混亂
character|n. 性格
characteristic|adj. 典型的
characterize|v. 描繪
charge|v. 收費
charity|n. 慈善
chart|n. 圖表
charter|n. 憲章
chase|v. 追逐
chat|v. 聊天
cheap|adj. 便宜的
cheat|v. 欺騙
check|v. 檢查
checkout|n. 結帳
cheer|v. 歡呼
cheerful|adj. 開朗的
chef|n. 廚師
chemical|adj. 化學的
chemist|n. 化學家
chemistry|n. 化學
cheque|n. 支票
cherish|v. 珍惜
chief|adj. 主要的
childhood|n. 童年
chill|n. 寒冷
choice|n. 選擇
choir|n. 合唱團
choose|v. 選擇
chore|n. 雜務
chronic|adj. 慢性的
circle|n. 圓圈
circuit|n. 電路
circular|adj. 圓形的
circulate|v. 循環
circulation|n. 循環
circumstance|n. 情況
cite|v. 引用
citizen|n. 公民
city|n. 城市
civic|adj. 城市的
civil|adj. 公民的
civilian|n. 平民
civilization|n. 文明
claim|v. 聲稱
clarify|v. 澄清
clarity|n. 清楚
clash|v. 衝突
classic|adj. 經典的
classical|adj. 古典的
classification|n. 分類
classify|v. 分類
clause|n. 條款
clean|adj. 乾淨的
clear|adj. 清楚的
clearance|n. 清除
clerk|n. 職員
clever|adj. 聰明的
click|v. 點擊
client|n. 客戶
clientele|n. 客戶群
climate|n. 氣候
climax|n. 頂點
climb|v. 攀登
cling|v. 緊抓
clinic|n. 診所
clip|n. 夾子
clock|n. 時鐘
close|adj. 靠近的
closet|n. 壁櫥
closure|n. 關閉
clothe|v. 給...穿衣
clothes|n. 衣服
clothing|n. 衣物
cloud|n. 雲
clue|n. 線索
clumsy|adj. 笨拙的
cluster|n. 簇
coach|n. 教練
coalition|n. 聯盟
coarse|adj. 粗糙的
coast|n. 海岸
code|n. 代碼
coffee|n. 咖啡
cognitive|adj. 認知的
cohere|v. 連貫
coherent|adj. 連貫的
cohesion|n. 凝聚力
cohesive|adj. 有凝聚力的
coincide|v. 同時發生
coincidence|n. 巧合
collaborate|v. 合作
collaboration|n. 合作
collapse|v. 倒塌
collar|n. 衣領
colleague|n. 同事
collect|v. 收集
collection|n. 收藏品
collective|adj. 集體的
collector|n. 收藏家
college|n. 大學
collide|v. 碰撞
collision|n. 碰撞
color|n. 顏色
column|n. 專欄
combat|n. 戰鬥
combination|n. 結合
combine|v. 結合
come|v. 來
comedy|n. 喜劇
comfort|n. 舒適
comfortable|adj. 舒服的
comic|adj. 滑稽的
command|v. 命令
commander|n. 指揮官
commemorate|v. 紀念
commence|v. 開始
commend|v. 稱讚
comment|n. 評論
commerce|n. 商業
commercial|adj. 商業的
commission|n. 佣金；委員會
commit|v. 犯
commitment|n. 承諾
committee|n. 委員會
commodity|n. 商品
common|adj. 常見的
commonly|adv. 通常
communicate|v. 溝通
communication|n. 溝通
commute|v. 通勤
commuter|n. 通勤者
compact|adj. 緊湊的
companion|n. 同伴
company|n. 公司
comparable|adj. 可比較的
comparative|adj. 比較的
compare|v. 比較
comparison|n. 比較
compass|n. 指南針
compassion|n. 同情
compatible|adj. 兼容的
compel|v. 強迫
compelling|adj. 引人注目的
compensate|v. 補償
compensation|n. 補償；薪酬
compete|v. 競爭
competence|n. 能力
competent|adj. 勝任的
competition|n. 競爭
competitive|adj. 有競爭力的
competitor|n. 競爭者
compile|v. 編譯
complain|v. 抱怨
complaint|n. 抱怨；投訴
complement|n. 補充物
complete|adj. 完整的
completion|n. 完成
complex|adj. 複雜的
complexity|n. 複雜性`,

// Unit 15
`compliance|n. 遵守；合規
complicate|v. 使複雜化
complicated|adj. 複雜的
complication|n. 併發症
compliment|n. 讚美
complimentary|adj. 免費的
comply|v. 遵守
component|n. 零件
compose|v. 組成
composer|n. 作曲家
composition|n. 作文
compound|n. 混合物
comprehend|v. 理解
comprehension|n. 理解
comprehensive|adj. 全面的
compress|v. 壓縮
comprise|v. 包含
compromise|n. 妥協
compulsory|adj. 義務的
compute|v. 計算
computer|n. 電腦
conceal|v. 隱藏
concede|v. 退讓
conceit|n. 自負
conceive|v. 構思
concentrate|v. 集中
concentration|n. 集中
concept|n. 概念
conception|n. 觀念
concern|v. 關心
concerning|prep. 關於
concert|n. 音樂會
concession|n. 讓步
concise|adj. 簡潔的
conclude|v. 結束
conclusion|n. 結論
conclusive|adj. 決定性的
concrete|adj. 具體的
concur|v. 同意
condemn|v. 譴責
condense|v. 壓縮
condition|n. 情況
conduct|v. 進行
conductor|n. 指揮
cone|n. 圓錐體
confer|v. 協商
conference|n. 會議
confess|v. 承認
confession|n. 承認
confide|v. 吐露
confidence|n. 信心
confident|adj. 自信的
confidential|adj. 機密的
configure|v. 配置
confine|v. 限制
confirm|v. 確認
confirmation|n. 確認
conflict|n. 衝突
conform|v. 遵守
conformity|n. 遵從
confront|v. 面對
confrontation|n. 對抗
confuse|v. 使困惑
confusion|n. 困惑
congratulate|v. 祝賀
congratulation|n. 祝賀
congregation|n. 集合
congress|n. 國會
connect|v. 連接
connection|n. 連接
conquer|v. 征服
conquest|n. 征服
conscience|n. 良心
conscientious|adj. 認真的
conscious|adj. 有意識的
consciousness|n. 意識
consecutive|adj. 連續的
consensus|n. 共識
consent|n. 同意
consequence|n. 結果
consequent|adj. 隨之發生的
consequently|adv. 因此
conservation|n. 保存
conservative|adj. 保守的
conserve|v. 保存
consider|v. 考慮
considerable|adj. 相當大的
considerably|adv. 相當地
considerate|adj. 體貼的
consideration|n. 考慮
consist|v. 組成
consistency|n. 一致性
consistent|adj. 一致的
console|v. 安慰
consolidate|v. 鞏固
conspicuous|adj. 顯著的
conspiracy|n. 陰謀
constant|adj. 不斷的
constantly|adv. 經常地
constitute|v. 構成
constitution|n. 憲法
constraint|n. 限制
construct|v. 建造
construction|n. 建設
constructive|adj. 建設性的
consult|v. 請教
consultant|n. 顧問
consultation|n. 諮詢
consume|v. 消耗
consumer|n. 消費者
consumption|n. 消費
contact|v. 接觸
contain|v. 包含
container|n. 容器
contaminate|v. 汙染
contemplate|v. 沉思
contemporary|adj. 當代的
contempt|n. 輕視
contend|v. 競爭
content|n. 內容
contention|n. 爭論
contest|n. 比賽
context|n. 背景
continent|n. 大陸
contingency|n. 意外事故
continue|v. 繼續
continuous|adj. 連續的
contract|n. 合約
contractor|n. 承包商
contradict|v. 反駁
contradiction|n. 矛盾
contrary|adj. 相反的
contrast|n. 對比
contribute|v. 貢獻
contribution|n. 貢獻
contributor|n. 貢獻者
contrive|v. 發明
control|v. 控制
controversial|adj. 有爭議的
controversy|n. 爭議
convene|v. 召集
convenience|n. 便利
convenient|adj. 方便的
convention|n. 慣例
conventional|adj. 傳統的
converge|v. 匯聚
conversation|n. 對話
converse|v. 交談
conversion|n. 轉換
convert|v. 轉換
convey|v. 傳達
convict|v. 定罪
conviction|n. 確信
convince|v. 使確信
convincing|adj. 令人信服的
cook|v. 烹調
cool|adj. 涼爽的
cooperate|v. 合作
cooperation|n. 合作
cooperative|adj. 合作的
coordinate|v. 協調
coordination|n. 協調
cop|n. 警察
cope|v. 應付
copy|n. 副本
copyright|n. 版權
core|n. 核心
corner|n. 角落
corporate|adj. 公司的
corporation|n. 公司；法人
corps|n. 部隊
correct|adj. 正確的
correction|n. 訂正
correlate|v. 使相關
correlation|n. 相關性
correspond|v. 符合
correspondence|n. 通信；信件
correspondent|n. 通訊記者
corridor|n. 走廊
corrupt|adj. 腐敗的
corruption|n. 腐敗
cost|n. 成本`,

// Unit 16
`costly|adj. 昂貴的
costume|n. 服裝
cottage|n. 小屋
cotton|n. 棉花
couch|n. 沙發
cough|v. 咳嗽
council|n. 議會
counsel|n. 建議
counseling|n. 輔導
counselor|n. 顧問
count|v. 計算
counter|n. 櫃台
counterpart|n. 對應的人或物
country|n. 國家
countryside|n. 鄉村
county|n. 縣
couple|n. 夫婦
courage|n. 勇氣
courier|n. 快遞員
course|n. 課程
court|n. 法庭
courtesy|n. 禮貌
cover|v. 覆蓋
coverage|n. 涵蓋範圍；保險範圍
coward|n. 懦夫
crack|v. 破裂
craft|n. 工藝
crash|v. 碰撞
crawl|v. 爬行
crazy|adj. 瘋狂的
create|v. 創造
creation|n. 創造
creative|adj. 有創造力的
creativity|n. 創造力
creator|n. 創造者
creature|n. 生物
credential|n. 憑證
credit|n. 信用
crew|n. 全體人員
crime|n. 犯罪
criminal|adj. 犯罪的
cripple|v. 使殘廢
crisis|n. 危機
crisp|adj. 脆的
criteria|n. 標準
criterion|n. 標準
critic|n. 評論家
critical|adj. 批評的
criticism|n. 批評
criticize|v. 批評
crop|n. 農作物
cross|v. 交叉
crowd|n. 人群
crowded|adj. 擁擠的
crucial|adj. 決定性的
crude|adj. 粗糙的
cruel|adj. 殘忍的
cruise|v. 巡航
crush|v. 壓碎
cry|v. 哭泣
crystal|n. 水晶
cube|n. 立方體
cue|n. 暗示
cultivate|v. 培養
cultivation|n. 培養
cultural|adj. 文化的
culture|n. 文化
cupboard|n. 櫥櫃
cure|v. 治療
curiosity|n. 好奇心
curious|adj. 好奇的
curl|v. 捲曲
currency|n. 貨幣
current|adj. 目前的
currently|adv. 目前
curriculum|n. 課程
curve|n. 曲線
custom|n. 習俗
customer|n. 顧客
customs|n. 海關
cut|v. 切割
cute|adj. 可愛的
cycle|n. 循環
cylinder|n. 圓柱體
daily|adj. 每天的
damage|n. 損害
danger|n. 危險
dangerous|adj. 危險的
dare|v. 敢
dark|adj. 黑暗的
dash|v. 猛衝
data|n. 數據
database|n. 資料庫
date|n. 日期
dawn|n. 黎明
dead|adj. 死的
deadline|n. 截止日期
deadly|adj. 致命的
deaf|adj. 聾的
deal|n. 交易
dealer|n. 經銷商
debate|n. 辯論
debris|n. 碎片
debt|n. 債務
debut|n. 初次登台
decade|n. 十年
decay|v. 腐爛
deceit|n. 欺騙
deceive|v. 欺騙
decent|adj. 體面的
decide|v. 決定
decision|n. 決定
decisive|adj. 決定性的
deck|n. 甲板
declaration|n. 宣佈
declare|v. 宣佈
decline|v. 下降
decorate|v. 裝飾
decoration|n. 裝飾
decrease|v. 減少
dedicate|v. 奉獻
dedication|n. 奉獻
deduct|v. 扣除
deduction|n. 扣除
deed|n. 行為
deem|v. 認為
deep|adj. 深的
deepen|v. 加深
deeply|adv. 深深地
deer|n. 鹿
default|n. 違約
defeat|v. 擊敗
defect|n. 缺點
defective|adj. 有缺陷的
defend|v. 防禦
defendant|n. 被告
defense|n. 防禦
defensive|adj. 防禦的
defer|v. 推遲
deficiency|n. 缺乏
deficit|n. 赤字
define|v. 定義
definite|adj. 明確的
definitely|adv. 肯定地
definition|n. 定義
degree|n. 程度
delay|v. 延遲
delegate|v. 委派
delegation|n. 代表團
delete|v. 刪除
deliberate|adj. 故意的
deliberately|adv. 故意地
delicate|adj. 精緻的
delicious|adj. 美味的
delight|n. 高興
delightful|adj. 令人愉快的
deliver|v. 遞送；交付
delivery|n. 遞送
demand|v. 要求
demanding|adj. 苛求的
democracy|n. 民主
democrat|n. 民主黨員
democratic|adj. 民主的
demographic|adj. 人口統計的
demolish|v. 拆除
demonstrate|v. 示範；證明
demonstration|n. 示範
denial|n. 否認
denounce|v. 譴責
dense|adj. 密集的
density|n. 密度
dentist|n. 牙醫
deny|v. 否認
depart|v. 離開
department|n. 部門
departure|n. 離開
depend|v. 依賴
dependable|adj. 可靠的
dependence|n. 依賴
dependent|adj. 依賴的
depict|v. 描繪
deplete|v. 耗盡
deploy|v. 部署
deployment|n. 部署
deposit|n. 訂金；存款
depreciate|v. 貶值
depress|v. 使沮喪
depression|n. 沮喪
deprive|v. 剝奪
depth|n. 深度
deputy|n. 副手
derive|v. 衍生
descend|v. 下降
describe|v. 描述
description|n. 描述
desert|n. 沙漠
deserve|v. 值得
design|v. 設計
designate|v. 指定
designer|n. 設計師
desirable|adj. 理想的
desire|v. 渴望
desk|n. 書桌
despair|n. 絕望
desperate|adj. 絕望的
despite|prep. 儘管
destination|n. 目的地
destiny|n. 命運
destroy|v. 破壞
destruction|n. 破壞`
];

let curUnit = 12;
let idCounter = 20200;
let newLines = [];

for (const unitLines of rawUnits) {
    const lines = unitLines.trim().split('\n');
    for (const line of lines) {
        if (!line.trim()) continue;
        const [en, zh] = line.split('|');
        if (!en || !zh) continue;
        const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
        newLines.push(`    { id: ${idCounter++}, en: '${esc(en.trim())}', kk: '', zh: '${esc(zh.trim())}', unit: ${curUnit}, example: '', exampleZh: '' }`);
    }
    curUnit++;
}

// read toeic_data.js
let content = fs.readFileSync('toeic_data.js', 'utf8');

// append directly inside the array
const arrayEnd = content.lastIndexOf('];');
const beforeEnd = content.substring(0, arrayEnd).trim();
const afterEnd = content.substring(arrayEnd);

// Add comma if needed
let finalContent = beforeEnd;
if (!finalContent.endsWith(',')) {
    finalContent += ',\\n';
} else {
    finalContent += '\\n';
}

finalContent += newLines.join(',\\n') + '\\n' + afterEnd;

fs.writeFileSync('toeic_data.js', finalContent, 'utf8');
console.log('Added 1000 words into toeic_data.js! Now units 12-16 exist.');

