// 多益常考單字 (單元 11)，格式: 單字|詞性 中文
const toeicRaw = `
accommodate|v. 容納；提供住宿
acquire|v. 取得；收購
adjacent|adj. 鄰近的
administration|n. 管理；行政
advertisement|n. 廣告
agenda|n. 議程
agreement|n. 協議；合約
allocate|v. 分配；撥出
amendment|n. 修正；修訂
annual|adj. 每年的
applicant|n. 申請人
appointment|n. 約會；任命
appraisal|n. 評估；考核
approval|n. 批准
assemble|v. 組裝；集合
assess|v. 評估
asset|n. 資產
attach|v. 附上；附加
attendee|n. 出席者
audit|n. 審計；v. 查帳
authorize|v. 授權；批准
availability|n. 可用性；空檔
backlog|n. 積壓的工作
balance|n. 餘額；平衡
banquet|n. 宴會
benefit|n. 福利；利益
bid|n. 投標；v. 出價
board|n. 董事會；v. 登機
booth|n. 攤位；小隔間
brochure|n. 小冊子
budget|n. 預算
bulletin|n. 公告
candidate|n. 候選人；應徵者
capacity|n. 容量；能力
cargo|n. 貨物
catalog|n. 目錄
catering|n. 外燴服務
certificate|n. 證書
clientele|n. 客戶群
colleague|n. 同事
commence|v. 開始
commission|n. 佣金；委員會
commute|v. 通勤
compensation|n. 補償；薪酬
competitive|adj. 有競爭力的
complaint|n. 抱怨；投訴
compliance|n. 遵守；合規
comprehensive|adj. 全面的
confidential|adj. 機密的
confirm|v. 確認
conference|n. 會議
consecutive|adj. 連續的
consultant|n. 顧問
consumer|n. 消費者
contract|n. 合約
convenience|n. 便利
corporation|n. 公司；法人
correspondence|n. 通信；信件
courier|n. 快遞員
coverage|n. 涵蓋範圍；保險範圍
customer|n. 顧客
deadline|n. 截止日期
deduct|v. 扣除
deliver|v. 遞送；交付
demonstrate|v. 示範；證明
department|n. 部門
deposit|n. 訂金；存款
designate|v. 指定
destination|n. 目的地
directory|n. 名錄；通訊錄
discount|n. 折扣
dispatch|v. 派遣；發送
distribute|v. 分發；分配
division|n. 部門；分割
document|n. 文件
domestic|adj. 國內的
downsize|v. 縮編；裁員
durable|adj. 耐用的
efficient|adj. 有效率的
eligible|adj. 有資格的
employee|n. 員工
enclose|v. 隨函附上
endorse|v. 背書；認可
enroll|v. 註冊；登記
ensure|v. 確保
entrepreneur|n. 企業家
equipment|n. 設備
estimate|n. 估價；v. 估計
evaluate|v. 評價
exceed|v. 超過
exhibition|n. 展覽
expand|v. 擴張
expenditure|n. 開支
expense|n. 費用
expire|v. 到期
facility|n. 設施
fiscal|adj. 財政的
flexible|adj. 彈性的
forecast|n. 預測
franchise|n. 特許經營；加盟
freight|n. 貨運
furnish|v. 配備家具；提供
generate|v. 產生
guarantee|n. 保證；v. 保證
headquarters|n. 總部
inquiry|n. 詢問
installation|n. 安裝
instruction|n. 指示；說明
insurance|n. 保險
inventory|n. 庫存；存貨
invoice|n. 發票；請款單
itinerary|n. 行程表
jeopardize|v. 危害
launch|v. 推出；發射
lease|n. 租約；v. 出租
liability|n. 責任；負債
logistics|n. 物流
maintenance|n. 維護
manufacture|v. 製造
margin|n. 利潤；邊緣
merchandise|n. 商品
merge|v. 合併
minutes|n. 會議記錄
negotiate|v. 協商；談判
notify|v. 通知
obligation|n. 義務
occupy|v. 佔用；佔據
operate|v. 操作；營運
order|n. 訂單；v. 訂購
outstanding|adj. 傑出的；未付的
overdue|adj. 逾期的
overtime|n. 加班
participate|v. 參加
partnership|n. 合夥關係
patron|n. 老主顧；贊助人
payroll|n. 薪資單
personnel|n. 人員；人事部
postpone|v. 延期
precaution|n. 預防措施
premises|n. 營業場所
presentation|n. 簡報
procedure|n. 程序
procurement|n. 採購
productivity|n. 生產力
profit|n. 利潤
promote|v. 晉升；促銷
promotion|n. 升遷；促銷
proposal|n. 提案
purchase|v. 購買
qualification|n. 資格
quotation|n. 報價
receipt|n. 收據
recipient|n. 收件人
recruit|v. 招募
refund|n. 退款
regulation|n. 規定
reimburse|v. 補償；報銷
reliable|adj. 可靠的
relocate|v. 搬遷
renew|v. 更新；續約
renovation|n. 整修
reputation|n. 名聲
require|v. 要求；需要
reservation|n. 預約
resign|v. 辭職
résumé|n. 履歷表
retail|n. 零售
revenue|n. 營收
revise|v. 修訂
salary|n. 薪水
schedule|n. 時程表
securities|n. 證券
shipment|n. 出貨；貨物
shortage|n. 短缺
specification|n. 規格
sponsor|n. 贊助者
staff|n. 員工
subscription|n. 訂閱
subsidiary|n. 子公司
supervisor|n. 主管
supplier|n. 供應商
surplus|n. 過剩；盈餘
tentative|adj. 暫定的
terminate|v. 終止
transaction|n. 交易
transfer|v. 轉移；調職
transit|n. 運輸；過境
turnover|n. 營業額；人員流動
upgrade|v. 升級
utility|n. 公用事業
vacancy|n. 職缺；空房
vendor|n. 供應商；小販
venue|n. 場地
verify|v. 驗證
warehouse|n. 倉庫
warranty|n. 保固
withdraw|v. 提領；撤回
workshop|n. 工作坊；研討會
`;

const toeicWordsDB = toeicRaw.trim().split('\n').map((line, i) => {
    const [en, zh] = line.split('|');
    return { id: 20001 + i, en: en.trim(), kk: '', zh: zh.trim(), unit: 11 };
});
